// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.7
// source: msg/smsg/smsg.proto

package smsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GaCeRespLogin_Error int32

const (
	GaCeRespLogin_Invalid GaCeRespLogin_Error = 0
)

// Enum value maps for GaCeRespLogin_Error.
var (
	GaCeRespLogin_Error_name = map[int32]string{
		0: "Invalid",
	}
	GaCeRespLogin_Error_value = map[string]int32{
		"Invalid": 0,
	}
)

func (x GaCeRespLogin_Error) Enum() *GaCeRespLogin_Error {
	p := new(GaCeRespLogin_Error)
	*p = x
	return p
}

func (x GaCeRespLogin_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GaCeRespLogin_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_smsg_smsg_proto_enumTypes[0].Descriptor()
}

func (GaCeRespLogin_Error) Type() protoreflect.EnumType {
	return &file_msg_smsg_smsg_proto_enumTypes[0]
}

func (x GaCeRespLogin_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GaCeRespLogin_Error.Descriptor instead.
func (GaCeRespLogin_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{2, 0}
}

type CeGamRespJoinGame_Error int32

const (
	CeGamRespJoinGame_Invalid      CeGamRespJoinGame_Error = 0
	CeGamRespJoinGame_GameNotExist CeGamRespJoinGame_Error = 1
)

// Enum value maps for CeGamRespJoinGame_Error.
var (
	CeGamRespJoinGame_Error_name = map[int32]string{
		0: "Invalid",
		1: "GameNotExist",
	}
	CeGamRespJoinGame_Error_value = map[string]int32{
		"Invalid":      0,
		"GameNotExist": 1,
	}
)

func (x CeGamRespJoinGame_Error) Enum() *CeGamRespJoinGame_Error {
	p := new(CeGamRespJoinGame_Error)
	*p = x
	return p
}

func (x CeGamRespJoinGame_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CeGamRespJoinGame_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_smsg_smsg_proto_enumTypes[1].Descriptor()
}

func (CeGamRespJoinGame_Error) Type() protoreflect.EnumType {
	return &file_msg_smsg_smsg_proto_enumTypes[1]
}

func (x CeGamRespJoinGame_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CeGamRespJoinGame_Error.Descriptor instead.
func (CeGamRespJoinGame_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{5, 0}
}

type AdRespMetrics_MetricsType int32

const (
	AdRespMetrics_Invalid     AdRespMetrics_MetricsType = 0
	AdRespMetrics_OnlineCount AdRespMetrics_MetricsType = 1 //在线人数
)

// Enum value maps for AdRespMetrics_MetricsType.
var (
	AdRespMetrics_MetricsType_name = map[int32]string{
		0: "Invalid",
		1: "OnlineCount",
	}
	AdRespMetrics_MetricsType_value = map[string]int32{
		"Invalid":     0,
		"OnlineCount": 1,
	}
)

func (x AdRespMetrics_MetricsType) Enum() *AdRespMetrics_MetricsType {
	p := new(AdRespMetrics_MetricsType)
	*p = x
	return p
}

func (x AdRespMetrics_MetricsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdRespMetrics_MetricsType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_smsg_smsg_proto_enumTypes[2].Descriptor()
}

func (AdRespMetrics_MetricsType) Type() protoreflect.EnumType {
	return &file_msg_smsg_smsg_proto_enumTypes[2]
}

func (x AdRespMetrics_MetricsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdRespMetrics_MetricsType.Descriptor instead.
func (AdRespMetrics_MetricsType) EnumDescriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{13, 0}
}

type Server2AllSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Server2AllSession) Reset() {
	*x = Server2AllSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server2AllSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server2AllSession) ProtoMessage() {}

func (x *Server2AllSession) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server2AllSession.ProtoReflect.Descriptor instead.
func (*Server2AllSession) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{0}
}

func (x *Server2AllSession) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GaCeReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sesid int32  `protobuf:"varint,1,opt,name=sesid,proto3" json:"sesid,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GaCeReqLogin) Reset() {
	*x = GaCeReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GaCeReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaCeReqLogin) ProtoMessage() {}

func (x *GaCeReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaCeReqLogin.ProtoReflect.Descriptor instead.
func (*GaCeReqLogin) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{1}
}

func (x *GaCeReqLogin) GetSesid() int32 {
	if x != nil {
		return x.Sesid
	}
	return 0
}

func (x *GaCeReqLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GaCeRespLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64              `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Err    GaCeRespLogin_Error `protobuf:"varint,2,opt,name=err,proto3,enum=smsg.GaCeRespLogin_Error" json:"err,omitempty"`
	Token  string              `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	InGame bool                `protobuf:"varint,4,opt,name=inGame,proto3" json:"inGame,omitempty"`
}

func (x *GaCeRespLogin) Reset() {
	*x = GaCeRespLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GaCeRespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaCeRespLogin) ProtoMessage() {}

func (x *GaCeRespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaCeRespLogin.ProtoReflect.Descriptor instead.
func (*GaCeRespLogin) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{2}
}

func (x *GaCeRespLogin) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GaCeRespLogin) GetErr() GaCeRespLogin_Error {
	if x != nil {
		return x.Err
	}
	return GaCeRespLogin_Invalid
}

func (x *GaCeRespLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GaCeRespLogin) GetInGame() bool {
	if x != nil {
		return x.InGame
	}
	return false
}

type CeGaBindGameServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sesid        int32 `protobuf:"varint,1,opt,name=sesid,proto3" json:"sesid,omitempty"`
	Gameserverid int32 `protobuf:"varint,2,opt,name=gameserverid,proto3" json:"gameserverid,omitempty"`
}

func (x *CeGaBindGameServer) Reset() {
	*x = CeGaBindGameServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CeGaBindGameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeGaBindGameServer) ProtoMessage() {}

func (x *CeGaBindGameServer) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeGaBindGameServer.ProtoReflect.Descriptor instead.
func (*CeGaBindGameServer) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{3}
}

func (x *CeGaBindGameServer) GetSesid() int32 {
	if x != nil {
		return x.Sesid
	}
	return 0
}

func (x *CeGaBindGameServer) GetGameserverid() int32 {
	if x != nil {
		return x.Gameserverid
	}
	return 0
}

type CeGamReqJoinGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid       uint64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Sesid        int32  `protobuf:"varint,2,opt,name=sesid,proto3" json:"sesid,omitempty"`
	Nickname     string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	GateServerid int32  `protobuf:"varint,4,opt,name=gateServerid,proto3" json:"gateServerid,omitempty"`
}

func (x *CeGamReqJoinGame) Reset() {
	*x = CeGamReqJoinGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CeGamReqJoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeGamReqJoinGame) ProtoMessage() {}

func (x *CeGamReqJoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeGamReqJoinGame.ProtoReflect.Descriptor instead.
func (*CeGamReqJoinGame) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{4}
}

func (x *CeGamReqJoinGame) GetUserid() uint64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *CeGamReqJoinGame) GetSesid() int32 {
	if x != nil {
		return x.Sesid
	}
	return 0
}

func (x *CeGamReqJoinGame) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CeGamReqJoinGame) GetGateServerid() int32 {
	if x != nil {
		return x.GateServerid
	}
	return 0
}

type CeGamRespJoinGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err    CeGamRespJoinGame_Error `protobuf:"varint,1,opt,name=err,proto3,enum=smsg.CeGamRespJoinGame_Error" json:"err,omitempty"`
	Gameid int64                   `protobuf:"varint,2,opt,name=gameid,proto3" json:"gameid,omitempty"`
}

func (x *CeGamRespJoinGame) Reset() {
	*x = CeGamRespJoinGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CeGamRespJoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeGamRespJoinGame) ProtoMessage() {}

func (x *CeGamRespJoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeGamRespJoinGame.ProtoReflect.Descriptor instead.
func (*CeGamRespJoinGame) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{5}
}

func (x *CeGamRespJoinGame) GetErr() CeGamRespJoinGame_Error {
	if x != nil {
		return x.Err
	}
	return CeGamRespJoinGame_Invalid
}

func (x *CeGamRespJoinGame) GetGameid() int64 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

type GamCeNoticeGameStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameid int64 `protobuf:"varint,1,opt,name=gameid,proto3" json:"gameid,omitempty"`
}

func (x *GamCeNoticeGameStart) Reset() {
	*x = GamCeNoticeGameStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamCeNoticeGameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamCeNoticeGameStart) ProtoMessage() {}

func (x *GamCeNoticeGameStart) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamCeNoticeGameStart.ProtoReflect.Descriptor instead.
func (*GamCeNoticeGameStart) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{6}
}

func (x *GamCeNoticeGameStart) GetGameid() int64 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

type GamCeNoticeGameEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gameid int64 `protobuf:"varint,1,opt,name=gameid,proto3" json:"gameid,omitempty"`
}

func (x *GamCeNoticeGameEnd) Reset() {
	*x = GamCeNoticeGameEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamCeNoticeGameEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamCeNoticeGameEnd) ProtoMessage() {}

func (x *GamCeNoticeGameEnd) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamCeNoticeGameEnd.ProtoReflect.Descriptor instead.
func (*GamCeNoticeGameEnd) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{7}
}

func (x *GamCeNoticeGameEnd) GetGameid() int64 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

type CeGameUserDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid uint64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
}

func (x *CeGameUserDisconnect) Reset() {
	*x = CeGameUserDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CeGameUserDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeGameUserDisconnect) ProtoMessage() {}

func (x *CeGameUserDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeGameUserDisconnect.ProtoReflect.Descriptor instead.
func (*CeGameUserDisconnect) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{8}
}

func (x *CeGameUserDisconnect) GetUserid() uint64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type CeGameUserReconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid    uint64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	GateID    int32  `protobuf:"varint,2,opt,name=gateID,proto3" json:"gateID,omitempty"`
	SessionID int32  `protobuf:"varint,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *CeGameUserReconnect) Reset() {
	*x = CeGameUserReconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CeGameUserReconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeGameUserReconnect) ProtoMessage() {}

func (x *CeGameUserReconnect) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeGameUserReconnect.ProtoReflect.Descriptor instead.
func (*CeGameUserReconnect) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{9}
}

func (x *CeGameUserReconnect) GetUserid() uint64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *CeGameUserReconnect) GetGateID() int32 {
	if x != nil {
		return x.GateID
	}
	return 0
}

func (x *CeGameUserReconnect) GetSessionID() int32 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type GaCeUserDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID int32 `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *GaCeUserDisconnect) Reset() {
	*x = GaCeUserDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GaCeUserDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaCeUserDisconnect) ProtoMessage() {}

func (x *GaCeUserDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaCeUserDisconnect.ProtoReflect.Descriptor instead.
func (*GaCeUserDisconnect) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{10}
}

func (x *GaCeUserDisconnect) GetSessionID() int32 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type CeGaCloseSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID int32 `protobuf:"varint,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
}

func (x *CeGaCloseSession) Reset() {
	*x = CeGaCloseSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CeGaCloseSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CeGaCloseSession) ProtoMessage() {}

func (x *CeGaCloseSession) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CeGaCloseSession.ProtoReflect.Descriptor instead.
func (*CeGaCloseSession) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{11}
}

func (x *CeGaCloseSession) GetSessionID() int32 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

type AdReqMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqTime int64 `protobuf:"varint,3,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
}

func (x *AdReqMetrics) Reset() {
	*x = AdReqMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdReqMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdReqMetrics) ProtoMessage() {}

func (x *AdReqMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdReqMetrics.ProtoReflect.Descriptor instead.
func (*AdReqMetrics) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{12}
}

func (x *AdReqMetrics) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

type AdRespMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics []*AdRespMetrics_Metrics `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	ReqTime int64                    `protobuf:"varint,2,opt,name=reqTime,proto3" json:"reqTime,omitempty"`
}

func (x *AdRespMetrics) Reset() {
	*x = AdRespMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdRespMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdRespMetrics) ProtoMessage() {}

func (x *AdRespMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdRespMetrics.ProtoReflect.Descriptor instead.
func (*AdRespMetrics) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{13}
}

func (x *AdRespMetrics) GetMetrics() []*AdRespMetrics_Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AdRespMetrics) GetReqTime() int64 {
	if x != nil {
		return x.ReqTime
	}
	return 0
}

type AdRespMetrics_Metrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   AdRespMetrics_MetricsType `protobuf:"varint,1,opt,name=key,proto3,enum=smsg.AdRespMetrics_MetricsType" json:"key,omitempty"`
	Value int32                     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AdRespMetrics_Metrics) Reset() {
	*x = AdRespMetrics_Metrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_smsg_smsg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdRespMetrics_Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdRespMetrics_Metrics) ProtoMessage() {}

func (x *AdRespMetrics_Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_msg_smsg_smsg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdRespMetrics_Metrics.ProtoReflect.Descriptor instead.
func (*AdRespMetrics_Metrics) Descriptor() ([]byte, []int) {
	return file_msg_smsg_smsg_proto_rawDescGZIP(), []int{13, 0}
}

func (x *AdRespMetrics_Metrics) GetKey() AdRespMetrics_MetricsType {
	if x != nil {
		return x.Key
	}
	return AdRespMetrics_Invalid
}

func (x *AdRespMetrics_Metrics) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_msg_smsg_smsg_proto protoreflect.FileDescriptor

var file_msg_smsg_smsg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x6d, 0x73, 0x67, 0x22, 0x27, 0x0a, 0x11, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x0c, 0x47, 0x61, 0x43, 0x65, 0x52, 0x65, 0x71, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x98, 0x01, 0x0a, 0x0d, 0x47, 0x61, 0x43, 0x65, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x47,
	0x61, 0x43, 0x65, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x6e, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x22, 0x4e, 0x0a, 0x12, 0x43,
	0x65, 0x47, 0x61, 0x42, 0x69, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x73, 0x65, 0x73, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x10,
	0x43, 0x65, 0x47, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x73, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x65, 0x73, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x69, 0x64, 0x22, 0x84,
	0x01, 0x0a, 0x11, 0x43, 0x65, 0x47, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x65, 0x47, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x22, 0x26, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x10, 0x01, 0x22, 0x2e, 0x0a, 0x14, 0x47, 0x61, 0x6d, 0x43, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x43, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x14, 0x43, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x64, 0x22, 0x63, 0x0a, 0x13, 0x43, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x67, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x32, 0x0a, 0x12, 0x47, 0x61, 0x43, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x10,
	0x43, 0x65, 0x47, 0x61, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x28,
	0x0a, 0x0c, 0x41, 0x64, 0x52, 0x65, 0x71, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x72, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x6d,
	0x73, 0x67, 0x2e, 0x41, 0x64, 0x52, 0x65, 0x73, 0x70, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x71, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x52, 0x0a, 0x07, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x31, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x73, 0x6d, 0x73, 0x67, 0x2e, 0x41, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x2b, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x01, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_smsg_smsg_proto_rawDescOnce sync.Once
	file_msg_smsg_smsg_proto_rawDescData = file_msg_smsg_smsg_proto_rawDesc
)

func file_msg_smsg_smsg_proto_rawDescGZIP() []byte {
	file_msg_smsg_smsg_proto_rawDescOnce.Do(func() {
		file_msg_smsg_smsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_smsg_smsg_proto_rawDescData)
	})
	return file_msg_smsg_smsg_proto_rawDescData
}

var file_msg_smsg_smsg_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_msg_smsg_smsg_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_msg_smsg_smsg_proto_goTypes = []interface{}{
	(GaCeRespLogin_Error)(0),       // 0: smsg.GaCeRespLogin.Error
	(CeGamRespJoinGame_Error)(0),   // 1: smsg.CeGamRespJoinGame.Error
	(AdRespMetrics_MetricsType)(0), // 2: smsg.AdRespMetrics.MetricsType
	(*Server2AllSession)(nil),      // 3: smsg.Server2AllSession
	(*GaCeReqLogin)(nil),           // 4: smsg.GaCeReqLogin
	(*GaCeRespLogin)(nil),          // 5: smsg.GaCeRespLogin
	(*CeGaBindGameServer)(nil),     // 6: smsg.CeGaBindGameServer
	(*CeGamReqJoinGame)(nil),       // 7: smsg.CeGamReqJoinGame
	(*CeGamRespJoinGame)(nil),      // 8: smsg.CeGamRespJoinGame
	(*GamCeNoticeGameStart)(nil),   // 9: smsg.GamCeNoticeGameStart
	(*GamCeNoticeGameEnd)(nil),     // 10: smsg.GamCeNoticeGameEnd
	(*CeGameUserDisconnect)(nil),   // 11: smsg.CeGameUserDisconnect
	(*CeGameUserReconnect)(nil),    // 12: smsg.CeGameUserReconnect
	(*GaCeUserDisconnect)(nil),     // 13: smsg.GaCeUserDisconnect
	(*CeGaCloseSession)(nil),       // 14: smsg.CeGaCloseSession
	(*AdReqMetrics)(nil),           // 15: smsg.AdReqMetrics
	(*AdRespMetrics)(nil),          // 16: smsg.AdRespMetrics
	(*AdRespMetrics_Metrics)(nil),  // 17: smsg.AdRespMetrics.Metrics
}
var file_msg_smsg_smsg_proto_depIdxs = []int32{
	0,  // 0: smsg.GaCeRespLogin.err:type_name -> smsg.GaCeRespLogin.Error
	1,  // 1: smsg.CeGamRespJoinGame.err:type_name -> smsg.CeGamRespJoinGame.Error
	17, // 2: smsg.AdRespMetrics.metrics:type_name -> smsg.AdRespMetrics.Metrics
	2,  // 3: smsg.AdRespMetrics.Metrics.key:type_name -> smsg.AdRespMetrics.MetricsType
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_msg_smsg_smsg_proto_init() }
func file_msg_smsg_smsg_proto_init() {
	if File_msg_smsg_smsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_smsg_smsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server2AllSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GaCeReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GaCeRespLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CeGaBindGameServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CeGamReqJoinGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CeGamRespJoinGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamCeNoticeGameStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamCeNoticeGameEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CeGameUserDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CeGameUserReconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GaCeUserDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CeGaCloseSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdReqMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdRespMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_smsg_smsg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdRespMetrics_Metrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_smsg_smsg_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_smsg_smsg_proto_goTypes,
		DependencyIndexes: file_msg_smsg_smsg_proto_depIdxs,
		EnumInfos:         file_msg_smsg_smsg_proto_enumTypes,
		MessageInfos:      file_msg_smsg_smsg_proto_msgTypes,
	}.Build()
	File_msg_smsg_smsg_proto = out.File
	file_msg_smsg_smsg_proto_rawDesc = nil
	file_msg_smsg_smsg_proto_goTypes = nil
	file_msg_smsg_smsg_proto_depIdxs = nil
}
