// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.7
// source: msg/cmsg/cmsg.proto

package cmsg

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RespLogin_Error int32

const (
	RespLogin_Invalid  RespLogin_Error = 0
	RespLogin_RPCError RespLogin_Error = 1
)

// Enum value maps for RespLogin_Error.
var (
	RespLogin_Error_name = map[int32]string{
		0: "Invalid",
		1: "RPCError",
	}
	RespLogin_Error_value = map[string]int32{
		"Invalid":  0,
		"RPCError": 1,
	}
)

func (x RespLogin_Error) Enum() *RespLogin_Error {
	p := new(RespLogin_Error)
	*p = x
	return p
}

func (x RespLogin_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespLogin_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[0].Descriptor()
}

func (RespLogin_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[0]
}

func (x RespLogin_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespLogin_Error.Descriptor instead.
func (RespLogin_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{1, 0}
}

type RespJoinGame_Error int32

const (
	RespJoinGame_Invalid        RespJoinGame_Error = 0
	RespJoinGame_UserNotExisted RespJoinGame_Error = 1
	RespJoinGame_AlreadyInGame  RespJoinGame_Error = 2
)

// Enum value maps for RespJoinGame_Error.
var (
	RespJoinGame_Error_name = map[int32]string{
		0: "Invalid",
		1: "UserNotExisted",
		2: "AlreadyInGame",
	}
	RespJoinGame_Error_value = map[string]int32{
		"Invalid":        0,
		"UserNotExisted": 1,
		"AlreadyInGame":  2,
	}
)

func (x RespJoinGame_Error) Enum() *RespJoinGame_Error {
	p := new(RespJoinGame_Error)
	*p = x
	return p
}

func (x RespJoinGame_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespJoinGame_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[1].Descriptor()
}

func (RespJoinGame_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[1]
}

func (x RespJoinGame_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespJoinGame_Error.Descriptor instead.
func (RespJoinGame_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{3, 0}
}

type RespEnterGame_Error int32

const (
	RespEnterGame_Invalid RespEnterGame_Error = 0
)

// Enum value maps for RespEnterGame_Error.
var (
	RespEnterGame_Error_name = map[int32]string{
		0: "Invalid",
	}
	RespEnterGame_Error_value = map[string]int32{
		"Invalid": 0,
	}
)

func (x RespEnterGame_Error) Enum() *RespEnterGame_Error {
	p := new(RespEnterGame_Error)
	*p = x
	return p
}

func (x RespEnterGame_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespEnterGame_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[2].Descriptor()
}

func (RespEnterGame_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[2]
}

func (x RespEnterGame_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespEnterGame_Error.Descriptor instead.
func (RespEnterGame_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{5, 0}
}

type RespGameScene_Error int32

const (
	RespGameScene_Invalid      RespGameScene_Error = 0
	RespGameScene_GameNotExist RespGameScene_Error = 1
)

// Enum value maps for RespGameScene_Error.
var (
	RespGameScene_Error_name = map[int32]string{
		0: "Invalid",
		1: "GameNotExist",
	}
	RespGameScene_Error_value = map[string]int32{
		"Invalid":      0,
		"GameNotExist": 1,
	}
)

func (x RespGameScene_Error) Enum() *RespGameScene_Error {
	p := new(RespGameScene_Error)
	*p = x
	return p
}

func (x RespGameScene_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespGameScene_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[3].Descriptor()
}

func (RespGameScene_Error) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[3]
}

func (x RespGameScene_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespGameScene_Error.Descriptor instead.
func (RespGameScene_Error) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{12, 0}
}

type SNoticeKickOut_Reason int32

const (
	SNoticeKickOut_Invalid SNoticeKickOut_Reason = 0
	SNoticeKickOut_Relogin SNoticeKickOut_Reason = 1 //重复登录被T出
)

// Enum value maps for SNoticeKickOut_Reason.
var (
	SNoticeKickOut_Reason_name = map[int32]string{
		0: "Invalid",
		1: "Relogin",
	}
	SNoticeKickOut_Reason_value = map[string]int32{
		"Invalid": 0,
		"Relogin": 1,
	}
)

func (x SNoticeKickOut_Reason) Enum() *SNoticeKickOut_Reason {
	p := new(SNoticeKickOut_Reason)
	*p = x
	return p
}

func (x SNoticeKickOut_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SNoticeKickOut_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_cmsg_cmsg_proto_enumTypes[4].Descriptor()
}

func (SNoticeKickOut_Reason) Type() protoreflect.EnumType {
	return &file_msg_cmsg_cmsg_proto_enumTypes[4]
}

func (x SNoticeKickOut_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SNoticeKickOut_Reason.Descriptor instead.
func (SNoticeKickOut_Reason) EnumDescriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{18, 0}
}

type ReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RespLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err    RespLogin_Error `protobuf:"varint,1,opt,name=err,proto3,enum=cmsg.RespLogin_Error" json:"err,omitempty"`
	UserID uint64          `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Token  string          `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	InGame bool            `protobuf:"varint,4,opt,name=inGame,proto3" json:"inGame,omitempty"` //是否正在游戏中
}

func (x *RespLogin) Reset() {
	*x = RespLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogin) ProtoMessage() {}

func (x *RespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogin.ProtoReflect.Descriptor instead.
func (*RespLogin) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{1}
}

func (x *RespLogin) GetErr() RespLogin_Error {
	if x != nil {
		return x.Err
	}
	return RespLogin_Invalid
}

func (x *RespLogin) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RespLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RespLogin) GetInGame() bool {
	if x != nil {
		return x.InGame
	}
	return false
}

type ReqJoinGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *ReqJoinGame) Reset() {
	*x = ReqJoinGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinGame) ProtoMessage() {}

func (x *ReqJoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinGame.ProtoReflect.Descriptor instead.
func (*ReqJoinGame) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{2}
}

func (x *ReqJoinGame) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RespJoinGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err      RespJoinGame_Error `protobuf:"varint,1,opt,name=err,proto3,enum=cmsg.RespJoinGame_Error" json:"err,omitempty"`
	Nickname string             `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *RespJoinGame) Reset() {
	*x = RespJoinGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinGame) ProtoMessage() {}

func (x *RespJoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinGame.ProtoReflect.Descriptor instead.
func (*RespJoinGame) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{3}
}

func (x *RespJoinGame) GetErr() RespJoinGame_Error {
	if x != nil {
		return x.Err
	}
	return RespJoinGame_Invalid
}

func (x *RespJoinGame) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type ReqEnterGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqEnterGame) Reset() {
	*x = ReqEnterGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqEnterGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEnterGame) ProtoMessage() {}

func (x *ReqEnterGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEnterGame.ProtoReflect.Descriptor instead.
func (*ReqEnterGame) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{4}
}

type RespEnterGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config      *RespEnterGame_Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	EntityID    int32                 `protobuf:"varint,2,opt,name=entityID,proto3" json:"entityID,omitempty"`
	GameLeftSec int32                 `protobuf:"varint,3,opt,name=gameLeftSec,proto3" json:"gameLeftSec,omitempty"`
	Dead        bool                  `protobuf:"varint,4,opt,name=dead,proto3" json:"dead,omitempty"` //是否已挂
	Err         RespEnterGame_Error   `protobuf:"varint,5,opt,name=err,proto3,enum=cmsg.RespEnterGame_Error" json:"err,omitempty"`
}

func (x *RespEnterGame) Reset() {
	*x = RespEnterGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespEnterGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespEnterGame) ProtoMessage() {}

func (x *RespEnterGame) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespEnterGame.ProtoReflect.Descriptor instead.
func (*RespEnterGame) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{5}
}

func (x *RespEnterGame) GetConfig() *RespEnterGame_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RespEnterGame) GetEntityID() int32 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *RespEnterGame) GetGameLeftSec() int32 {
	if x != nil {
		return x.GameLeftSec
	}
	return 0
}

func (x *RespEnterGame) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *RespEnterGame) GetErr() RespEnterGame_Error {
	if x != nil {
		return x.Err
	}
	return RespEnterGame_Invalid
}

type Rank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Rank_Item `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Rank) Reset() {
	*x = Rank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank) ProtoMessage() {}

func (x *Rank) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank.ProtoReflect.Descriptor instead.
func (*Rank) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{6}
}

func (x *Rank) GetList() []*Rank_Item {
	if x != nil {
		return x.List
	}
	return nil
}

type SNoticeGameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverReason  int32                   `protobuf:"varint,1,opt,name=overReason,proto3" json:"overReason,omitempty"`
	Killer      *SNoticeGameOver_Killer `protobuf:"bytes,2,opt,name=killer,proto3" json:"killer,omitempty"`
	GameLeftSec int32                   `protobuf:"varint,3,opt,name=gameLeftSec,proto3" json:"gameLeftSec,omitempty"`
	Rank        *Rank                   `protobuf:"bytes,4,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *SNoticeGameOver) Reset() {
	*x = SNoticeGameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeGameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeGameOver) ProtoMessage() {}

func (x *SNoticeGameOver) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeGameOver.ProtoReflect.Descriptor instead.
func (*SNoticeGameOver) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{7}
}

func (x *SNoticeGameOver) GetOverReason() int32 {
	if x != nil {
		return x.OverReason
	}
	return 0
}

func (x *SNoticeGameOver) GetKiller() *SNoticeGameOver_Killer {
	if x != nil {
		return x.Killer
	}
	return nil
}

func (x *SNoticeGameOver) GetGameLeftSec() int32 {
	if x != nil {
		return x.GameLeftSec
	}
	return 0
}

func (x *SNoticeGameOver) GetRank() *Rank {
	if x != nil {
		return x.Rank
	}
	return nil
}

type ReqMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PressTime      float32 `protobuf:"fixed32,1,opt,name=pressTime,proto3" json:"pressTime,omitempty"`
	TargetRotation float32 `protobuf:"fixed32,2,opt,name=targetRotation,proto3" json:"targetRotation,omitempty"`
	InputSeqID     int32   `protobuf:"varint,3,opt,name=inputSeqID,proto3" json:"inputSeqID,omitempty"`
}

func (x *ReqMove) Reset() {
	*x = ReqMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMove) ProtoMessage() {}

func (x *ReqMove) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMove.ProtoReflect.Descriptor instead.
func (*ReqMove) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{8}
}

func (x *ReqMove) GetPressTime() float32 {
	if x != nil {
		return x.PressTime
	}
	return 0
}

func (x *ReqMove) GetTargetRotation() float32 {
	if x != nil {
		return x.TargetRotation
	}
	return 0
}

func (x *ReqMove) GetInputSeqID() int32 {
	if x != nil {
		return x.InputSeqID
	}
	return 0
}

type ReqShoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqShoot) Reset() {
	*x = ReqShoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqShoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqShoot) ProtoMessage() {}

func (x *ReqShoot) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqShoot.ProtoReflect.Descriptor instead.
func (*ReqShoot) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{9}
}

type ReqJump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqJump) Reset() {
	*x = ReqJump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJump) ProtoMessage() {}

func (x *ReqJump) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJump.ProtoReflect.Descriptor instead.
func (*ReqJump) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{10}
}

//请求游戏场景信息
type ReqGameScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqGameScene) Reset() {
	*x = ReqGameScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGameScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGameScene) ProtoMessage() {}

func (x *ReqGameScene) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGameScene.ProtoReflect.Descriptor instead.
func (*ReqGameScene) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{11}
}

//断线重连，请求当前场景信息
type RespGameScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities    []*Entity           `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	GameLeftSec int32               `protobuf:"varint,2,opt,name=gameLeftSec,proto3" json:"gameLeftSec,omitempty"`
	Err         RespGameScene_Error `protobuf:"varint,3,opt,name=err,proto3,enum=cmsg.RespGameScene_Error" json:"err,omitempty"`
}

func (x *RespGameScene) Reset() {
	*x = RespGameScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGameScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGameScene) ProtoMessage() {}

func (x *RespGameScene) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGameScene.ProtoReflect.Descriptor instead.
func (*RespGameScene) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{12}
}

func (x *RespGameScene) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *RespGameScene) GetGameLeftSec() int32 {
	if x != nil {
		return x.GameLeftSec
	}
	return 0
}

func (x *RespGameScene) GetErr() RespGameScene_Error {
	if x != nil {
		return x.Err
	}
	return RespGameScene_Invalid
}

//子弹发送
type SNoticeShoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X               float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y               float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Rotation        float32 `protobuf:"fixed32,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	BulletID        int32   `protobuf:"varint,4,opt,name=bulletID,proto3" json:"bulletID,omitempty"`
	CreatorEntityID int32   `protobuf:"varint,5,opt,name=creatorEntityID,proto3" json:"creatorEntityID,omitempty"`
}

func (x *SNoticeShoot) Reset() {
	*x = SNoticeShoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeShoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeShoot) ProtoMessage() {}

func (x *SNoticeShoot) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeShoot.ProtoReflect.Descriptor instead.
func (*SNoticeShoot) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{13}
}

func (x *SNoticeShoot) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SNoticeShoot) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SNoticeShoot) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *SNoticeShoot) GetBulletID() int32 {
	if x != nil {
		return x.BulletID
	}
	return 0
}

func (x *SNoticeShoot) GetCreatorEntityID() int32 {
	if x != nil {
		return x.CreatorEntityID
	}
	return 0
}

type SNoticeWorldChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteBullets   []int32                      `protobuf:"varint,1,rep,packed,name=deleteBullets,proto3" json:"deleteBullets,omitempty"`
	DeleteEntities  []int32                      `protobuf:"varint,2,rep,packed,name=deleteEntities,proto3" json:"deleteEntities,omitempty"`
	ChangedEntities []*SNoticeWorldChange_Entity `protobuf:"bytes,3,rep,name=changedEntities,proto3" json:"changedEntities,omitempty"`
}

func (x *SNoticeWorldChange) Reset() {
	*x = SNoticeWorldChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeWorldChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeWorldChange) ProtoMessage() {}

func (x *SNoticeWorldChange) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeWorldChange.ProtoReflect.Descriptor instead.
func (*SNoticeWorldChange) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{14}
}

func (x *SNoticeWorldChange) GetDeleteBullets() []int32 {
	if x != nil {
		return x.DeleteBullets
	}
	return nil
}

func (x *SNoticeWorldChange) GetDeleteEntities() []int32 {
	if x != nil {
		return x.DeleteEntities
	}
	return nil
}

func (x *SNoticeWorldChange) GetChangedEntities() []*SNoticeWorldChange_Entity {
	if x != nil {
		return x.ChangedEntities
	}
	return nil
}

type SNoticeWorldPos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities             []*SNoticeWorldPos_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	LastProcessedInputID int32                     `protobuf:"varint,2,opt,name=lastProcessedInputID,proto3" json:"lastProcessedInputID,omitempty"`
}

func (x *SNoticeWorldPos) Reset() {
	*x = SNoticeWorldPos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeWorldPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeWorldPos) ProtoMessage() {}

func (x *SNoticeWorldPos) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeWorldPos.ProtoReflect.Descriptor instead.
func (*SNoticeWorldPos) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{15}
}

func (x *SNoticeWorldPos) GetEntities() []*SNoticeWorldPos_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SNoticeWorldPos) GetLastProcessedInputID() int32 {
	if x != nil {
		return x.LastProcessedInputID
	}
	return 0
}

type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountType int32   `protobuf:"varint,2,opt,name=accountType,proto3" json:"accountType,omitempty"`
	HeadImgUrl  string  `protobuf:"bytes,3,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	Rotation    float32 `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Hp          int32   `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	Score       int32   `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	KillCount   int32   `protobuf:"varint,7,opt,name=killCount,proto3" json:"killCount,omitempty"`
	Dead        bool    `protobuf:"varint,8,opt,name=dead,proto3" json:"dead,omitempty"`
	Protected   bool    `protobuf:"varint,9,opt,name=protected,proto3" json:"protected,omitempty"`
	X           float32 `protobuf:"fixed32,10,opt,name=x,proto3" json:"x,omitempty"`
	Y           float32 `protobuf:"fixed32,11,opt,name=y,proto3" json:"y,omitempty"`
	Nickname    string  `protobuf:"bytes,12,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{16}
}

func (x *Entity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entity) GetAccountType() int32 {
	if x != nil {
		return x.AccountType
	}
	return 0
}

func (x *Entity) GetHeadImgUrl() string {
	if x != nil {
		return x.HeadImgUrl
	}
	return ""
}

func (x *Entity) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Entity) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Entity) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Entity) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *Entity) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *Entity) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *Entity) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Entity) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Entity) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type SNoticeNewEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *SNoticeNewEntity) Reset() {
	*x = SNoticeNewEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeNewEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeNewEntity) ProtoMessage() {}

func (x *SNoticeNewEntity) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeNewEntity.ProtoReflect.Descriptor instead.
func (*SNoticeNewEntity) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{17}
}

func (x *SNoticeNewEntity) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

//通知被T出
type SNoticeKickOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason SNoticeKickOut_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=cmsg.SNoticeKickOut_Reason" json:"reason,omitempty"`
}

func (x *SNoticeKickOut) Reset() {
	*x = SNoticeKickOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeKickOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeKickOut) ProtoMessage() {}

func (x *SNoticeKickOut) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeKickOut.ProtoReflect.Descriptor instead.
func (*SNoticeKickOut) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{18}
}

func (x *SNoticeKickOut) GetReason() SNoticeKickOut_Reason {
	if x != nil {
		return x.Reason
	}
	return SNoticeKickOut_Invalid
}

type RespEnterGame_Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BulletLiveTime    int32   `protobuf:"varint,1,opt,name=bulletLiveTime,proto3" json:"bulletLiveTime,omitempty"`
	RotationDelta     float32 `protobuf:"fixed32,2,opt,name=rotationDelta,proto3" json:"rotationDelta,omitempty"`
	EntitySpeed       int32   `protobuf:"varint,3,opt,name=entitySpeed,proto3" json:"entitySpeed,omitempty"`
	BulletSpeed       int32   `protobuf:"varint,4,opt,name=bulletSpeed,proto3" json:"bulletSpeed,omitempty"`
	NoticePosDuration int32   `protobuf:"varint,5,opt,name=noticePosDuration,proto3" json:"noticePosDuration,omitempty"`
	ProtectTime       int32   `protobuf:"varint,6,opt,name=protectTime,proto3" json:"protectTime,omitempty"`
	EntityRadius      int32   `protobuf:"varint,7,opt,name=entityRadius,proto3" json:"entityRadius,omitempty"`
}

func (x *RespEnterGame_Config) Reset() {
	*x = RespEnterGame_Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespEnterGame_Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespEnterGame_Config) ProtoMessage() {}

func (x *RespEnterGame_Config) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespEnterGame_Config.ProtoReflect.Descriptor instead.
func (*RespEnterGame_Config) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RespEnterGame_Config) GetBulletLiveTime() int32 {
	if x != nil {
		return x.BulletLiveTime
	}
	return 0
}

func (x *RespEnterGame_Config) GetRotationDelta() float32 {
	if x != nil {
		return x.RotationDelta
	}
	return 0
}

func (x *RespEnterGame_Config) GetEntitySpeed() int32 {
	if x != nil {
		return x.EntitySpeed
	}
	return 0
}

func (x *RespEnterGame_Config) GetBulletSpeed() int32 {
	if x != nil {
		return x.BulletSpeed
	}
	return 0
}

func (x *RespEnterGame_Config) GetNoticePosDuration() int32 {
	if x != nil {
		return x.NoticePosDuration
	}
	return 0
}

func (x *RespEnterGame_Config) GetProtectTime() int32 {
	if x != nil {
		return x.ProtectTime
	}
	return 0
}

func (x *RespEnterGame_Config) GetEntityRadius() int32 {
	if x != nil {
		return x.EntityRadius
	}
	return 0
}

type Rank_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityID   int32  `protobuf:"varint,1,opt,name=entityID,proto3" json:"entityID,omitempty"`
	Score      int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank       int32  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	KillCount  int32  `protobuf:"varint,4,opt,name=killCount,proto3" json:"killCount,omitempty"`
	HeadImgUrl string `protobuf:"bytes,5,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	Nickname   string `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *Rank_Item) Reset() {
	*x = Rank_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rank_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rank_Item) ProtoMessage() {}

func (x *Rank_Item) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rank_Item.ProtoReflect.Descriptor instead.
func (*Rank_Item) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Rank_Item) GetEntityID() int32 {
	if x != nil {
		return x.EntityID
	}
	return 0
}

func (x *Rank_Item) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Rank_Item) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Rank_Item) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *Rank_Item) GetHeadImgUrl() string {
	if x != nil {
		return x.HeadImgUrl
	}
	return ""
}

func (x *Rank_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type SNoticeGameOver_Killer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountType int32  `protobuf:"varint,1,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Nickname    string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	HeadImgUrl  string `protobuf:"bytes,3,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	Hp          int32  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
}

func (x *SNoticeGameOver_Killer) Reset() {
	*x = SNoticeGameOver_Killer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeGameOver_Killer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeGameOver_Killer) ProtoMessage() {}

func (x *SNoticeGameOver_Killer) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeGameOver_Killer.ProtoReflect.Descriptor instead.
func (*SNoticeGameOver_Killer) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SNoticeGameOver_Killer) GetAccountType() int32 {
	if x != nil {
		return x.AccountType
	}
	return 0
}

func (x *SNoticeGameOver_Killer) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SNoticeGameOver_Killer) GetHeadImgUrl() string {
	if x != nil {
		return x.HeadImgUrl
	}
	return ""
}

func (x *SNoticeGameOver_Killer) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type SNoticeWorldChange_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hp        int32 `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	Score     int32 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	KillCount int32 `protobuf:"varint,4,opt,name=killCount,proto3" json:"killCount,omitempty"`
}

func (x *SNoticeWorldChange_Entity) Reset() {
	*x = SNoticeWorldChange_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeWorldChange_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeWorldChange_Entity) ProtoMessage() {}

func (x *SNoticeWorldChange_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeWorldChange_Entity.ProtoReflect.Descriptor instead.
func (*SNoticeWorldChange_Entity) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{14, 0}
}

func (x *SNoticeWorldChange_Entity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SNoticeWorldChange_Entity) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *SNoticeWorldChange_Entity) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SNoticeWorldChange_Entity) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

type SNoticeWorldPos_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X        float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Rotation float32 `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
}

func (x *SNoticeWorldPos_Entity) Reset() {
	*x = SNoticeWorldPos_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_cmsg_cmsg_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SNoticeWorldPos_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticeWorldPos_Entity) ProtoMessage() {}

func (x *SNoticeWorldPos_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_msg_cmsg_cmsg_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticeWorldPos_Entity.ProtoReflect.Descriptor instead.
func (*SNoticeWorldPos_Entity) Descriptor() ([]byte, []int) {
	return file_msg_cmsg_cmsg_proto_rawDescGZIP(), []int{15, 0}
}

func (x *SNoticeWorldPos_Entity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SNoticeWorldPos_Entity) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SNoticeWorldPos_Entity) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SNoticeWorldPos_Entity) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

var File_msg_cmsg_cmsg_proto protoreflect.FileDescriptor

var file_msg_cmsg_cmsg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6d, 0x73, 0x67, 0x22, 0x20, 0x0a, 0x08, 0x52,
	0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x9e, 0x01,
	0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x50, 0x43, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x22, 0x29,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d,
	0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x02, 0x22,
	0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x22,
	0xe9, 0x03, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d,
	0x65, 0x12, 0x32, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x65, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74,
	0x53, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x64, 0x65, 0x61, 0x64, 0x12, 0x2b, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x1a, 0x8e, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x26, 0x0a, 0x0e, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x4c, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x4c,
	0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d,
	0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x20, 0x0a,
	0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x70, 0x65, 0x65, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x73, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x6e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x73, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x61, 0x64, 0x69, 0x75,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0b,
	0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x22, 0xd4, 0x01, 0x0a, 0x04,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0xa6, 0x01, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x69, 0x6c, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6b, 0x69, 0x6c,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6d,
	0x67, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65, 0x61, 0x64,
	0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xa1, 0x02, 0x0a, 0x0f, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x47, 0x61,
	0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x06, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x2e, 0x4b, 0x69,
	0x6c, 0x6c, 0x65, 0x72, 0x52, 0x06, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x67, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x65, 0x63, 0x12, 0x1e,
	0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63,
	0x6d, 0x73, 0x67, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x1a, 0x76,
	0x0a, 0x06, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6d,
	0x67, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65, 0x61, 0x64,
	0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x22, 0x6f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x4d, 0x6f, 0x76,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x53, 0x65, 0x71, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x53, 0x65, 0x71, 0x49, 0x44, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x53, 0x68,
	0x6f, 0x6f, 0x74, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x4a, 0x75, 0x6d, 0x70, 0x22, 0x0e,
	0x0a, 0x0c, 0x52, 0x65, 0x71, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x22, 0xb0,
	0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x12, 0x28, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x61,
	0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x67, 0x61, 0x6d, 0x65, 0x4c, 0x65, 0x66, 0x74, 0x53, 0x65, 0x63, 0x12, 0x2b, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6d, 0x73, 0x67,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x26, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10,
	0x01, 0x22, 0x8c, 0x01, 0x0a, 0x0c, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x53, 0x68, 0x6f,
	0x6f, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75,
	0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x75,
	0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x44,
	0x22, 0x8b, 0x02, 0x0a, 0x12, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x12, 0x26, 0x0a,
	0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x0f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x1a, 0x5c, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xd1,
	0x01, 0x0a, 0x0f, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50,
	0x6f, 0x73, 0x12, 0x38, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x14,
	0x6c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x6c, 0x61, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x49, 0x44,
	0x1a, 0x50, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xa4, 0x02, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x68,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64,
	0x65, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x10, 0x53, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x24, 0x0a,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x69, 0x0a, 0x0e, 0x53, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x4b, 0x69,
	0x63, 0x6b, 0x4f, 0x75, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x63, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x06, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_cmsg_cmsg_proto_rawDescOnce sync.Once
	file_msg_cmsg_cmsg_proto_rawDescData = file_msg_cmsg_cmsg_proto_rawDesc
)

func file_msg_cmsg_cmsg_proto_rawDescGZIP() []byte {
	file_msg_cmsg_cmsg_proto_rawDescOnce.Do(func() {
		file_msg_cmsg_cmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_cmsg_cmsg_proto_rawDescData)
	})
	return file_msg_cmsg_cmsg_proto_rawDescData
}

var file_msg_cmsg_cmsg_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_msg_cmsg_cmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_msg_cmsg_cmsg_proto_goTypes = []interface{}{
	(RespLogin_Error)(0),              // 0: cmsg.RespLogin.Error
	(RespJoinGame_Error)(0),           // 1: cmsg.RespJoinGame.Error
	(RespEnterGame_Error)(0),          // 2: cmsg.RespEnterGame.Error
	(RespGameScene_Error)(0),          // 3: cmsg.RespGameScene.Error
	(SNoticeKickOut_Reason)(0),        // 4: cmsg.SNoticeKickOut.Reason
	(*ReqLogin)(nil),                  // 5: cmsg.ReqLogin
	(*RespLogin)(nil),                 // 6: cmsg.RespLogin
	(*ReqJoinGame)(nil),               // 7: cmsg.ReqJoinGame
	(*RespJoinGame)(nil),              // 8: cmsg.RespJoinGame
	(*ReqEnterGame)(nil),              // 9: cmsg.ReqEnterGame
	(*RespEnterGame)(nil),             // 10: cmsg.RespEnterGame
	(*Rank)(nil),                      // 11: cmsg.Rank
	(*SNoticeGameOver)(nil),           // 12: cmsg.SNoticeGameOver
	(*ReqMove)(nil),                   // 13: cmsg.ReqMove
	(*ReqShoot)(nil),                  // 14: cmsg.ReqShoot
	(*ReqJump)(nil),                   // 15: cmsg.ReqJump
	(*ReqGameScene)(nil),              // 16: cmsg.ReqGameScene
	(*RespGameScene)(nil),             // 17: cmsg.RespGameScene
	(*SNoticeShoot)(nil),              // 18: cmsg.SNoticeShoot
	(*SNoticeWorldChange)(nil),        // 19: cmsg.SNoticeWorldChange
	(*SNoticeWorldPos)(nil),           // 20: cmsg.SNoticeWorldPos
	(*Entity)(nil),                    // 21: cmsg.Entity
	(*SNoticeNewEntity)(nil),          // 22: cmsg.SNoticeNewEntity
	(*SNoticeKickOut)(nil),            // 23: cmsg.SNoticeKickOut
	(*RespEnterGame_Config)(nil),      // 24: cmsg.RespEnterGame.Config
	(*Rank_Item)(nil),                 // 25: cmsg.Rank.Item
	(*SNoticeGameOver_Killer)(nil),    // 26: cmsg.SNoticeGameOver.Killer
	(*SNoticeWorldChange_Entity)(nil), // 27: cmsg.SNoticeWorldChange.Entity
	(*SNoticeWorldPos_Entity)(nil),    // 28: cmsg.SNoticeWorldPos.Entity
}
var file_msg_cmsg_cmsg_proto_depIdxs = []int32{
	0,  // 0: cmsg.RespLogin.err:type_name -> cmsg.RespLogin.Error
	1,  // 1: cmsg.RespJoinGame.err:type_name -> cmsg.RespJoinGame.Error
	24, // 2: cmsg.RespEnterGame.config:type_name -> cmsg.RespEnterGame.Config
	2,  // 3: cmsg.RespEnterGame.err:type_name -> cmsg.RespEnterGame.Error
	25, // 4: cmsg.Rank.list:type_name -> cmsg.Rank.Item
	26, // 5: cmsg.SNoticeGameOver.killer:type_name -> cmsg.SNoticeGameOver.Killer
	11, // 6: cmsg.SNoticeGameOver.rank:type_name -> cmsg.Rank
	21, // 7: cmsg.RespGameScene.entities:type_name -> cmsg.Entity
	3,  // 8: cmsg.RespGameScene.err:type_name -> cmsg.RespGameScene.Error
	27, // 9: cmsg.SNoticeWorldChange.changedEntities:type_name -> cmsg.SNoticeWorldChange.Entity
	28, // 10: cmsg.SNoticeWorldPos.entities:type_name -> cmsg.SNoticeWorldPos.Entity
	21, // 11: cmsg.SNoticeNewEntity.entity:type_name -> cmsg.Entity
	4,  // 12: cmsg.SNoticeKickOut.reason:type_name -> cmsg.SNoticeKickOut.Reason
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_msg_cmsg_cmsg_proto_init() }
func file_msg_cmsg_cmsg_proto_init() {
	if File_msg_cmsg_cmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_cmsg_cmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJoinGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqEnterGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespEnterGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeGameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqShoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGameScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespGameScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeShoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeWorldChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeWorldPos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeNewEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeKickOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespEnterGame_Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rank_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeGameOver_Killer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeWorldChange_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_cmsg_cmsg_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SNoticeWorldPos_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_cmsg_cmsg_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_cmsg_cmsg_proto_goTypes,
		DependencyIndexes: file_msg_cmsg_cmsg_proto_depIdxs,
		EnumInfos:         file_msg_cmsg_cmsg_proto_enumTypes,
		MessageInfos:      file_msg_cmsg_cmsg_proto_msgTypes,
	}.Build()
	File_msg_cmsg_cmsg_proto = out.File
	file_msg_cmsg_cmsg_proto_rawDesc = nil
	file_msg_cmsg_cmsg_proto_goTypes = nil
	file_msg_cmsg_cmsg_proto_depIdxs = nil
}
